### PR TITLE
installation: pinning of elasticsearch version

### PR DESCRIPTION
**Pull request by jirikuncar**
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>

### CODE REVIEW

**Comment by jirikuncar** [comment]
@inveniosoftware/maintainers please have a look so we can release this quickly before pinning it in all dependent packages.

**Comment by nharraud** [comment]
No problem for B2Share. We pinned it the same way.

**Comment by PXke** [comment]
Same here, we did the same so no problems for us. 👍

**Comment by jirikuncar** [comment]
> No problem for B2Share. We pinned it the same way.

@nharraud it's not for overlays, that should have compiled dependencies anyway, but for all packages that depend on Invenio-Search.

**Comment by egabancho** [comment]
LGTM

**Comment by jirikuncar** [comment]
Thanks for LGTM @egabancho. I am going to merge and prepare quick release so we don't have to pin `elasticsearch` in other packages.

**Pull request merged**
