### PR TITLE
global: initial refactoring

### PR DESCRIPTION
**Pull request by jirikuncar**
- [ ] ~~port celery tasks for indexing from `invenio-records<1.0.0`~~
- [x] implement cli for creating indexes in elastic search

### CODE REVIEW

**Comment by jirikuncar** [comment]
@eamonnmag can you have a look if it covers everything from https://github.com/HEPData/hepdata/blob/master/hepdata/ext/elasticsearch/query_builder.py so far? Thanks

**Comment by jirikuncar** [comment]
@egabancho @lnielsen @eamonnmag @nharraud  please check https://github.com/jirikuncar/invenio-search/blob/next/examples/app.py and let me know if you can build a search-ui in similar way. Thanks

**Comment by nharraud** [comment]
The `__getitem__` feels kind of strange. I had to guess and go check in the code to see that it was manipulating the query's body and returning itself instead of returning a list of items. Why not use named parameters when creating the query and setters to later override the value if needed. This is especially true as the provided slice is not used for sorting the result and many valid slices don't make sense here (ex `[3:1]`, `[1::]` or `[-10:12]`).

**Comment by eamonnmag** [comment]
I think it's nice.Also, @jirikuncar, if the sort field doesn't exist in elastic search, it crashes, which is pretty crap. So this case needs to be caught. I think the caller should catch the exception though and deal with it rather than dealing with it in your code. @jstypka, what do you think of the query builder? Anything missing?

**Comment by jstypka** [comment]
It looks fine to me. It doesn't do a lot of the stuff that HEPData uses e.g. adding aggregations (for facets), highlights and filters. We also have two different indices `publication` and `datatable` with child-parent relation that enforce some special query treatment, but that might be unusual enough not to put it into general Invenio code. The sorting and paging looks good :+1:

**Comment by eamonnmag** [comment]
@jstypka indeed. @jirikuncar is adding in the highlights though. We can see if we can converge at some point. But that can wait until we go to invenio 3.

**Comment by nharraud** [comment]
The api looks good. The two advanced use cases I've thought of can be addressed with it. Those are:
- filtering the AST before building the query so that private records fields cannot be used by user queries. This is possible by using a dedicated Query Enhancer.
- use different Query Enhancers depending on the type of record. This is possible by giving the type as a parameter to the `Query` constructor or by calling `build` and enabling the enhancers when needed.

**Comment by nharraud** [comment]
@jstypka The aggregations could be either added by an Enhancer after giving additional parameters to `Query.build` or analyzing the query. It is also possible to replace the query parser if users can specify the aggregations. Same for parent-child relationships, but maybe more complex.

**Comment by jirikuncar** [comment]
- @eamonnmag @jstypka: I have added the `highlight` method.
- @egabancho: there is a simple example of "autoindexer" for Invenio-Records. One can add more examples later - index selector, "run-as-celery-task", etc.
- @lnielsen please `:shipit:` :wink:

**Comment by kaplun** [comment]
cc: @Panos512, @jmartinm: to be studied, so we know what is going to be in Invenio 3.0

**Pull request merged**
