### PR TITLE
global: fix import of invenio_upgrader

### PR DESCRIPTION
**Pull request by eamonnmag**
* FIX: import of invenio_upgrader

Signed-off-by: Eamonn Maguire eamonnmag@gmail.com

### CODE REVIEW

**Comment by jirikuncar** [comment]
@eamonnmag the correct commit messages are important otherwise person who will release the package can't use `kwalitee prepare release` for generating `RELEASE-NOTES.rst`. Thank you for your cooperation.

**Comment by tiborsimko** [comment]
Can you please repush with:

- `FIX Fixes...`
- `Eamonn <Maguire eamonnmag@gmail.com>`

**Comment by eamonnmag** [comment]
Done.

**Comment by tiborsimko** [comment]
Thanks.  This is only cosmetics, but since we generate release notes automatically, it's better to get it right from the get-go...

**Pull request merged**
