### PR TITLE
ext: fix error reporting

### PR DESCRIPTION
**Pull request by jrcastro2**

### CODE REVIEW

**Comment by utnapischtim** [comment]
may i ask which error this is fixing?

**Comment by jrcastro2** [comment]
> may i ask which error this is fixing?

Sure, it's simply fixing the error reporting to use a list instead of an iterator, by using the iterator, once consumed, it's empty and when trying to display the changes it will be an empty list so it's a bit confusing. Converting it to a list alllows to display the list of changes when raising the `NotAllowedMappingUpdate` so that we can easily review them and understand it.

**Comment by kpsherva** [comment]
interesting catch, thanks for fixing it!
LGTM, only needs black upgrade and remove python 3.7 from the CI matrix  to pass the tests

**Review by kpsherva — APPROVED** [review]

**Comment by utnapischtim** [comment]
> > may i ask which error this is fixing?
> 
> Sure, it's simply fixing the error reporting to use a list instead of an iterator, by using the iterator, once consumed, it's empty and when trying to display the changes it will be an empty list so it's a bit confusing. Converting it to a list alllows to display the list of changes when raising the `NotAllowedMappingUpdate` so that we can easily review them and understand it.

thank you for the explanation. i really thought that this has already been done some months ago. i imagined i've seen this somewhere before but can't remember where.

**Pull request merged**
